require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'
install! 'cocoapods', :deterministic_uuids => false

abstract_target 'BaseStructureCommonPods' do
  use_expo_modules!
  post_integrate do |installer|
    begin
    	expo_patch_react_imports!(installer)
    rescue => e
    	Pod::UI.warn e
    end
  end
  config = use_native_modules!
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => FlipperConfiguration.enabled,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'BaseStructureTests' do
    inherit! :complete
    # Pods for testing
  end

  target 'BaseStructureDev' do
  end  

  target 'BaseStructureStg' do
  end  

  target 'BaseStructure' do
  end  

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
